name: pokedex_cv_v01
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0
  http: ^1.2.2
  provider: ^6.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/background_list/normal.png
    - assets/background_list/fire.png
    - assets/background_list/water.png
    - assets/background_list/electric.png
    - assets/background_list/grass.png
    - assets/background_list/ice.png
    - assets/background_list/fighting.png
    - assets/background_list/poison.png
    - assets/background_list/ground.png
    - assets/background_list/flying.png
    - assets/background_list/psychic.png
    - assets/background_list/bug.png
    - assets/background_list/rock.png
    - assets/background_list/ghost.png
    - assets/background_list/dragon.png
    - assets/background_list/dark.png
    - assets/background_list/steel.png
    - assets/background_list/fairy.png
    - assets/general/white_pokeball.png
    - assets/general/red_pokeball.png
    - assets/general/bgPoke.png
    - assets/types_icons/normal.png
    - assets/types_icons/fire.png
    - assets/types_icons/water.png
    - assets/types_icons/electric.png
    - assets/types_icons/grass.png
    - assets/types_icons/ice.png
    - assets/types_icons/fighting.png
    - assets/types_icons/poison.png
    - assets/types_icons/ground.png
    - assets/types_icons/flying.png
    - assets/types_icons/psychic.png
    - assets/types_icons/bug.png
    - assets/types_icons/rock.png
    - assets/types_icons/ghost.png
    - assets/types_icons/dragon.png
    - assets/types_icons/dark.png
    - assets/types_icons/steel.png
    - assets/types_icons/fairy.png
    - assets/types_large/normal.png
    - assets/types_large/fire.png
    - assets/types_large/water.png
    - assets/types_large/electric.png
    - assets/types_large/grass.png
    - assets/types_large/ice.png
    - assets/types_large/fighting.png
    - assets/types_large/poison.png
    - assets/types_large/ground.png
    - assets/types_large/flying.png
    - assets/types_large/psychic.png
    - assets/types_large/bug.png
    - assets/types_large/rock.png
    - assets/types_large/ghost.png
    - assets/types_large/dragon.png
    - assets/types_large/dark.png
    - assets/types_large/steel.png
    - assets/types_large/fairy.png
    - assets/types_large/all.png
    - assets/generations/gen1.png
    - assets/generations/gen2.png
    - assets/generations/gen3.png
    - assets/generations/gen4.png
    - assets/generations/gen5.png
    - assets/generations/gen6.png
    - assets/generations/gen7.png
    - assets/generations/gen8.png
    - assets/generations/gen9.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
